// The map function is called once for each input file.
// The contents of the input file are processed to produce key-value pairs
// which are fed to reducer tasks.
pub fn map(filename: String, contents: String) -> Vec<KeyValue> {
    // TODO: simple word count - map each word to "1"
    todo!();
}

// The reduce function is called once for each key generated by map tasks with
// a list of all the values created for that key by any map task.
pub fn reduce(key: String, values: Vec<String>) -> String {
    // TODO: the count is just length of values
    todo!();
}
